export const API_ROUTES = {
  catalogueConfig: '/api/catalogue-config',
  auth: {
    register: '/api/auth/register',
    login: '/api/auth/login',
    forgotPassword: '/api/auth/forgot-password',
    resetPassword: '/api/auth/reset-password',
    me: '/api/auth/me',
    updateMe: '/api/auth/me',
    changePassword: '/api/auth/me/password',
  },
  projects: {
    list: '/api/projects',
    detail: (id) => `/api/projects/${id}`,
    recapPdf: (id) => `/api/projects/${id}/recap.pdf`,
  },
  products: {
    list: (projectId) => `/api/projects/${projectId}/products`,
    detail: (projectId, productId) => `/api/projects/${projectId}/products/${productId}`,
  },
  supplier: {
    me: '/api/supplier/me',
    workspace: '/api/supplier/workspace',
    products: '/api/supplier/products',
    product: (id) => `/api/supplier/products/${id}`,
    productPublication: (id) => `/api/supplier/products/${id}/publication`,
    productImages: (id) => `/api/supplier/products/${id}/images`,
    files: '/api/supplier/files',
    clients: {
      details: (clientId) => `/api/supplier/clients/${clientId}`,
    },
  },
  catalogue: {
    products: '/api/catalogue/products',
    product: (id) => `/api/catalogue/products/${id}`,
  },
  simulations: {
    create: '/api/simulations',
    myCount: '/api/simulations/my-count',
  },
  demandes: {
    listMine: '/api/demandes/me',
    create: '/api/demandes',
    messages: (id) => `/api/demandes/${id}/messages`,
    read: (id) => `/api/demandes/${id}/read`,
    hide: (id) => `/api/demandes/${id}`,
  },
  support: {
    listMine: '/api/support-items/me',
    create: '/api/support-items',
    messages: (id) => `/api/support-items/${id}/messages`,
    read: (id) => `/api/support-items/${id}/read`,
  },
  admin: {
    users: '/api/admin/users',
    user: (id) => `/api/admin/users/${id}`,
    userRole: (id) => `/api/admin/users/${id}/role`,
    permanentDeleteUser: (id) => `/api/admin/users/${id}/permanent`,
    suppliers: '/api/admin/suppliers',
    supplier: (id) => `/api/admin/suppliers/${id}`,
    permanentDeleteSupplier: (id) => `/api/admin/suppliers/${id}/permanent`,
    products: '/api/admin/products',
    product: (id) => `/api/admin/products/${id}`,
    simulations: '/api/admin/simulations',
    simulation: (id) => `/api/admin/simulations/${id}`,
    supportItems: '/api/admin/support-items',
    supportItem: (id) => `/api/admin/support-items/${id}`,
  },
};
