export const ADMIN_TRANSLATIONS = {
  fr: {
    pageTitles: {
      '/admin/dashboard': 'Tableau de bord admin',
      '/admin/catalogue/products': 'Articles',
      '/admin/suppliers': 'Fournisseurs',
      '/admin/users': 'Administration utilisateurs',
      '/admin/simulations': 'Simulations',
      '/admin/support': 'Support',
      '/admin/settings': 'Paramètres',
      fallback: 'Administration',
    },
    sidebar: {
      section: 'Administration',
      dashboard: 'Tableau de bord',
      articles: 'Articles',
      suppliers: 'Fournisseurs',
      suppliersList: 'Liste fournisseurs',
      users: 'Utilisateurs',
      simulations: 'Simulations',
      support: 'Support',
      settings: 'Paramètres',
      logout: 'Déconnexion',
    },
    search: {
      placeholder: (page) => `Rechercher dans ${page.toLowerCase()}`,
      message: (query) => (query ? `Recherche admin : ${query}` : 'Saisissez un mot-clé pour rechercher.'),
    },
    notifications: {
      title: 'Notifications admin',
      close: 'Fermer les notifications',
      empty: 'Aucune nouvelle notification backoffice.',
      publication: 'Publication fournisseur',
      newUser: 'Nouvelle inscription user',
      newFeedback: (role) => `Nouveau feedback ${role === 'supplier' ? 'fournisseur' : 'user'}`,
    },
    support: {
      eyebrow: 'Assistance', title: 'Support', listTitle: 'Feedbacks reçus',
      empty: 'Aucun feedback reçu.', loading: 'Chargement des feedbacks...',
      deleted: 'Feedback supprimé.', replySent: 'Réponse envoyée.', updated: 'Feedback mis à jour.',
    },
    common: {
      close: 'Fermer',
      cancel: 'Annuler',
      send: 'Envoyer',
      save: 'Sauvegarder',
      saving: 'Sauvegarde...',
      message: 'Message',
      reply: 'Répondre',
      passwordModal: {
        eyebrow: 'Sécurité',
        title: 'Modifier le mot de passe',
        currentPassword: 'Mot de passe actuel',
        newPassword: 'Nouveau mot de passe',
        confirmPassword: 'Confirmer le nouveau mot de passe',
        mismatch: 'Les nouveaux mots de passe ne correspondent pas.',
        saved: 'Mot de passe sauvegardé.',
        saveError: 'Impossible de modifier le mot de passe.',
      },
    },
    users: {
      statusActive: 'Actif',
      statusInactive: 'Inactif',
      statusBlocked: 'Bloqué',
      statusMissing: 'Inexistant',
      permanentDelete: 'Supprimer définitivement',
      restore: 'Restaurer',
      delete: 'Supprimer',
    },
    suppliers: {
      statusMissing: 'Inexistant',
      permanentDelete: 'Supprimer définitivement',
      restore: 'Restaurer',
      delete: 'Supprimer',
    },
    settings: {
      title: 'Paramètres',
      section: 'Général',
      locations: 'Emplacements',
      timezone: 'Fuseau horaire',
      language: 'Langue',
      policy: 'Politique',
      policyDescription: 'CGU, confidentialité, conditions fournisseurs et mentions légales.',
      password: 'Mot de passe',
      passwordDescription: 'Modifier le mot de passe de connexion',
      passwordUpdated: 'Mot de passe mis à jour.',
      policiesSynced: 'Politiques synchronisées.',
    },
    settingsModals: {
      profileSaved: 'Profil administrateur sauvegardé.',
      profileTitle: 'Coordonnées administrateur',
      generalInfo: 'Informations générales',
      fullName: 'Nom complet',
      email: 'Adresse e-mail',
      phone: 'Téléphone',
      accountContext: 'Contexte du compte',
      role: 'Rôle',
      superAdmin: 'Super Administrateur',
      scope: 'Portée',
      scopeDescription: 'Catalogue, utilisateurs, fournisseurs et simulations',
      locationSaved: 'Emplacement admin sauvegardé.',
      locationTitle: 'Emplacements admin',
      organizationName: "Nom de l'organisation",
      countryRegion: 'Pays/région',
      address: 'Adresse',
      addressPlaceholder: 'Adresse du bureau admin',
      neighborhood: 'Quartier',
      city: 'Ville',
      policyDeleted: 'Politique supprimée.',
      policyUpdated: 'Politique modifiée.',
      policyCreated: 'Politique créée.',
      backToPolicies: 'Retour aux politiques',
      editPolicy: 'Modifier une politique',
      policiesTitle: 'Politiques admin',
      requiredTitle: 'Titre',
      summary: 'Résumé',
      content: 'Contenu',
      englishVersion: 'Version anglaise',
      englishTitle: 'Titre anglais',
      englishSummary: 'Résumé anglais',
      englishContent: 'Contenu anglais',
      save: 'Enregistrer',
      emptyContent: 'Aucun contenu renseigné.',
      addPolicy: 'Ajouter une politique',
      noSummary: 'Aucun résumé renseigné.',
      actions: 'Actions',
      edit: 'Modifier',
      delete: 'Supprimer',
      emptyPolicies: 'Aucune politique configurée.',
    },
  },
  en: {
    pageTitles: {
      '/admin/dashboard': 'Admin dashboard',
      '/admin/catalogue/products': 'Articles',
      '/admin/suppliers': 'Suppliers',
      '/admin/users': 'User management',
      '/admin/simulations': 'Simulations',
      '/admin/support': 'Support',
      '/admin/settings': 'Settings',
      fallback: 'Administration',
    },
    sidebar: {
      section: 'Administration',
      dashboard: 'Dashboard',
      articles: 'Articles',
      suppliers: 'Suppliers',
      suppliersList: 'Supplier list',
      users: 'Users',
      simulations: 'Simulations',
      support: 'Support',
      settings: 'Settings',
      logout: 'Logout',
    },
    search: {
      placeholder: (page) => `Search in ${page.toLowerCase()}`,
      message: (query) => (query ? `Admin search: ${query}` : 'Enter a keyword to search.'),
    },
    notifications: {
      title: 'Admin notifications',
      close: 'Close notifications',
      empty: 'No new backoffice notification.',
      publication: 'Supplier publication',
      newUser: 'New user signup',
      newFeedback: (role) => `New ${role === 'supplier' ? 'supplier' : 'user'} feedback`,
    },
    support: {
      eyebrow: 'Help desk', title: 'Support', listTitle: 'Received feedback',
      empty: 'No feedback received.', loading: 'Loading feedback...',
      deleted: 'Feedback deleted.', replySent: 'Reply sent.', updated: 'Feedback updated.',
    },
    common: {
      close: 'Close',
      cancel: 'Cancel',
      send: 'Send',
      save: 'Save',
      saving: 'Saving...',
      message: 'Message',
      reply: 'Reply',
      passwordModal: {
        eyebrow: 'Security',
        title: 'Change password',
        currentPassword: 'Current password',
        newPassword: 'New password',
        confirmPassword: 'Confirm new password',
        mismatch: 'The new passwords do not match.',
        saved: 'Password saved.',
        saveError: 'Unable to change password.',
      },
    },
    users: {
      statusActive: 'Active',
      statusInactive: 'Inactive',
      statusBlocked: 'Blocked',
      statusMissing: 'Missing',
      permanentDelete: 'Delete permanently',
      restore: 'Restore',
      delete: 'Delete',
    },
    suppliers: {
      statusMissing: 'Missing',
      permanentDelete: 'Delete permanently',
      restore: 'Restore',
      delete: 'Delete',
    },
    settings: {
      title: 'Settings',
      section: 'General',
      locations: 'Locations',
      timezone: 'Time zone',
      language: 'Language',
      policy: 'Policy',
      policyDescription: 'Terms, privacy, supplier conditions and legal notices.',
      password: 'Password',
      passwordDescription: 'Change the sign-in password',
      passwordUpdated: 'Password updated.',
      policiesSynced: 'Policies synchronized.',
    },
    settingsModals: {
      profileSaved: 'Administrator profile saved.',
      profileTitle: 'Administrator contact details',
      generalInfo: 'General information',
      fullName: 'Full name',
      email: 'Email address',
      phone: 'Phone',
      accountContext: 'Account context',
      role: 'Role',
      superAdmin: 'Super administrator',
      scope: 'Scope',
      scopeDescription: 'Catalogue, users, suppliers and simulations',
      locationSaved: 'Admin location saved.',
      locationTitle: 'Admin locations',
      organizationName: 'Organization name',
      countryRegion: 'Country/region',
      address: 'Address',
      addressPlaceholder: 'Admin office address',
      neighborhood: 'Neighborhood',
      city: 'City',
      policyDeleted: 'Policy deleted.',
      policyUpdated: 'Policy updated.',
      policyCreated: 'Policy created.',
      backToPolicies: 'Back to policies',
      editPolicy: 'Edit a policy',
      policiesTitle: 'Admin policies',
      requiredTitle: 'Title',
      summary: 'Summary',
      content: 'Content',
      englishVersion: 'English version',
      englishTitle: 'English title',
      englishSummary: 'English summary',
      englishContent: 'English content',
      save: 'Save',
      emptyContent: 'No content provided.',
      addPolicy: 'Add policy',
      noSummary: 'No summary provided.',
      actions: 'Actions',
      edit: 'Edit',
      delete: 'Delete',
      emptyPolicies: 'No policy configured.',
    },
  },
};

export function normalizeAdminLanguage(language) {
  return String(language || '').toLowerCase().startsWith('ang') || String(language || '').toLowerCase().startsWith('en')
    ? 'en'
    : 'fr';
}

export function getAdminLanguage(adminData) {
  return normalizeAdminLanguage(adminData?.adminSettings?.settings?.language);
}

export function getAdminTranslations(adminDataOrLanguage) {
  const language = typeof adminDataOrLanguage === 'string'
    ? normalizeAdminLanguage(adminDataOrLanguage)
    : getAdminLanguage(adminDataOrLanguage);

  return ADMIN_TRANSLATIONS[language] || ADMIN_TRANSLATIONS.fr;
}
