export const SUPPLIER_LANGUAGE_LABELS = {
  fr: 'Français',
  en: 'Anglais',
};

export const SUPPLIER_TRANSLATIONS = {
  fr: {
    pageTitles: {
      '/supplier/dashboard': 'Tableau de bord',
      '/supplier/shop': 'Ma boutique',
      '/supplier/products': 'Produits',
      '/supplier/clients': 'Clients',
      '/supplier/demande': 'Demande',
      '/supplier/content/files': 'Fichiers',
      '/supplier/support': 'Support',
      '/supplier/settings': 'Paramètres',
      fallback: 'Espace supplier',
    },
    sidebar: {
      section: 'Boutique',
      dashboard: 'Tableau de bord',
      shop: 'Ma boutique',
      products: 'Produits',
      clients: 'Clients',
      demande: 'Demande',
      content: 'Contenu',
      files: 'Fichiers',
      support: 'Support',
      settings: 'Paramètres',
      logout: 'Déconnexion',
    },
    settings: {
      title: 'Paramètres',
      section: 'Général',
      location: 'Emplacements',
      timezone: 'Fuseau horaire',
      language: 'Langue',
      policy: 'Politique',
      policyDescription: 'CGU, confidentialité, fournisseurs et mentions légales',
      password: 'Mot de passe',
      passwordDescription: 'Modifier le mot de passe de connexion',
      passwordUpdated: 'Mot de passe mis à jour.',
    },
    search: {
      placeholder: (page) => `Rechercher dans ${page.toLowerCase()}`,
      message: (query) => (query ? `Recherche supplier : ${query}` : 'Saisissez un mot-clé pour rechercher.'),
    },
    notifications: {
      title: 'Notifications supplier',
      closeAll: 'Tout fermer',
      empty: 'Aucune nouvelle notification boutique.',
      refused: 'Publication refusée',
    },
    support: {
      eyebrow: 'Assistance boutique', title: 'Support', leaveComment: 'Laisser un commentaire',
      listTitle: 'Feedbacks boutique', empty: 'Aucun feedback fournisseur envoyé pour le moment.',
      placeholder: 'Partagez votre feedback sur votre espace fournisseur.',
      adminReply: 'Réponse admin', delete: 'Supprimer de ma liste',
      sent: 'Merci pour votre feedback', replySent: 'Réponse envoyée.',
    },
    common: {
      close: 'Fermer',
      cancel: 'Annuler',
      send: 'Envoyer',
      save: 'Sauvegarder',
      saving: 'Sauvegarde...',
      message: 'Message',
      you: 'Vous',
      passwordModal: {
        eyebrow: 'Sécurité',
        title: 'Modifier le mot de passe',
        currentPassword: 'Mot de passe actuel',
        newPassword: 'Nouveau mot de passe',
        confirmPassword: 'Confirmer le nouveau mot de passe',
        mismatch: 'Les nouveaux mots de passe ne correspondent pas.',
        saved: 'Mot de passe sauvegardé.',
        saveError: 'Impossible de modifier le mot de passe.',
      },
    },
    demand: {
      eyebrow: 'Demandes clients', title: 'Demandes reçues', loading: 'Chargement des demandes...',
      empty: 'Aucune demande reçue pour le moment.', newMessage: 'Nouvelle demande', readLabel: 'Message lu',
      noProject: 'Projet non renseigné', noMessage: 'Aucun message renseigné',
      noConversationMessage: 'Aucun message dans cette conversation.', placeholder: 'Écrivez votre réponse au client…',
      badgeNewRequests: (count) => `${count} nouvelle${count > 1 ? 's' : ''} demande${count > 1 ? 's' : ''}`,
      messageSent: 'Message envoyé.',
      conversationHidden: 'Conversation supprimée de votre liste.',
      deleteTitle: 'Supprimer de ma liste',
    },
    productForm: {
      addTitle: 'Ajouter un produit',
      editTitle: 'Modifier un produit',
      backLabel: 'Retour aux produits',
      title: 'Titre',
      titlePlaceholder: 'Ex: Canapé 3 places Oslo',
      description: 'Description',
      descriptionPlaceholder: 'Ajoutez une description complète du produit.',
      formattingToolsLabel: 'Outils de mise en forme de la description',
      paragraph: 'Paragraphe',
      heading: 'Titre',
      media: 'Supports multimédias',
      import: 'Importer',
      mediaHint: 'Nombre illimité d’images JPG, PNG ou WebP. 5 Mo maximum par fichier.',
      selectedFiles: (count, max) => (
        max === 'illimité'
          ? `${count} fichier(s) sélectionné(s) · import illimité`
          : `${count}/${max} fichier(s) sélectionné(s)`
      ),
      deleteFile: (name) => `Supprimer ${name}`,
      deleteExistingImage: (index) => `Supprimer l'image existante ${index}`,
      category: 'Catégorie',
      categoryPlaceholder: 'Choisir une catégorie de produits',
      price: 'Prix',
      organization: 'Organisation du produit',
      availability: 'Disponibilité',
      availabilityPlaceholder: 'Choisir une disponibilité',
      room: 'Pièce',
      roomPlaceholder: 'Choisir une pièce',
      supplier: 'Fournisseur',
      range: 'Gamme',
      rangePlaceholder: 'Choisir une gamme',
      cancel: 'Annuler',
      publish: 'Publier',
      requiredError: 'Tous les champs sont requis, y compris au moins une image.',
      missingProduct: 'Produit introuvable.',
      loadError: 'Impossible de charger le produit.',
      imageDeleteError: "Impossible de supprimer l'image.",
      saveError: "Impossible d'enregistrer le produit.",
      serverErrorTitle: 'Un problème est survenu lors du chargement de cette page',
      serverErrorMessage: "Un problème technique a empêché le chargement de cette page. Essayez de recharger cette page ou d'accéder à une autre page.",
      retry: 'Réessayer',
    },
  },
  en: {
    pageTitles: {
      '/supplier/dashboard': 'Dashboard',
      '/supplier/shop': 'My shop',
      '/supplier/products': 'Products',
      '/supplier/clients': 'Customers',
      '/supplier/demande': 'Request',
      '/supplier/content/files': 'Files',
      '/supplier/support': 'Support',
      '/supplier/settings': 'Settings',
      fallback: 'Supplier space',
    },
    sidebar: {
      section: 'Shop',
      dashboard: 'Dashboard',
      shop: 'My shop',
      products: 'Products',
      clients: 'Customers',
      demande: 'Request',
      content: 'Content',
      files: 'Files',
      support: 'Support',
      settings: 'Settings',
      logout: 'Logout',
    },
    settings: {
      title: 'Settings',
      section: 'General',
      location: 'Locations',
      timezone: 'Time zone',
      language: 'Language',
      policy: 'Policy',
      policyDescription: 'Terms, privacy, supplier conditions and legal notices',
      password: 'Password',
      passwordDescription: 'Change the sign-in password',
      passwordUpdated: 'Password updated.',
    },
    search: {
      placeholder: (page) => `Search in ${page.toLowerCase()}`,
      message: (query) => (query ? `Supplier search: ${query}` : 'Enter a keyword to search.'),
    },
    notifications: {
      title: 'Supplier notifications',
      closeAll: 'Close all',
      empty: 'No new shop notification.',
      refused: 'Publication refused',
    },
    support: {
      eyebrow: 'Shop support', title: 'Support', leaveComment: 'Leave a comment',
      listTitle: 'Shop feedback', empty: 'No supplier feedback sent yet.',
      placeholder: 'Share feedback about your supplier workspace.',
      adminReply: 'Admin reply', delete: 'Remove from my list',
      sent: 'Thank you for your feedback', replySent: 'Reply sent.',
    },
    common: {
      close: 'Close',
      cancel: 'Cancel',
      send: 'Send',
      save: 'Save',
      saving: 'Saving...',
      message: 'Message',
      you: 'You',
      passwordModal: {
        eyebrow: 'Security',
        title: 'Change password',
        currentPassword: 'Current password',
        newPassword: 'New password',
        confirmPassword: 'Confirm new password',
        mismatch: 'The new passwords do not match.',
        saved: 'Password saved.',
        saveError: 'Unable to change password.',
      },
    },
    demand: {
      eyebrow: 'Customer requests', title: 'Received requests', loading: 'Loading requests...',
      empty: 'No requests received yet.', newMessage: 'New request', readLabel: 'Message read',
      noProject: 'Project not specified', noMessage: 'No message',
      noConversationMessage: 'No messages in this conversation.', placeholder: 'Write your reply to the customer…',
      badgeNewRequests: (count) => `${count} new request${count > 1 ? 's' : ''}`,
      messageSent: 'Message sent.',
      conversationHidden: 'Conversation removed from your list.',
      deleteTitle: 'Remove from my list',
    },
    productForm: {
      addTitle: 'Add product',
      editTitle: 'Edit product',
      backLabel: 'Back to products',
      title: 'Title',
      titlePlaceholder: 'Ex: Oslo 3-seat sofa',
      description: 'Description',
      descriptionPlaceholder: 'Add a complete product description.',
      formattingToolsLabel: 'Description formatting tools',
      paragraph: 'Paragraph',
      heading: 'Heading',
      media: 'Media',
      import: 'Import',
      mediaHint: 'Unlimited JPG, PNG or WebP images. 5 MB maximum per file.',
      selectedFiles: (count, max) => (
        max === 'illimité'
          ? `${count} file(s) selected · unlimited import`
          : `${count}/${max} file(s) selected`
      ),
      deleteFile: (name) => `Remove ${name}`,
      deleteExistingImage: (index) => `Remove existing image ${index}`,
      category: 'Category',
      categoryPlaceholder: 'Choose a product category',
      price: 'Price',
      organization: 'Product organization',
      availability: 'Availability',
      availabilityPlaceholder: 'Choose an availability',
      room: 'Room',
      roomPlaceholder: 'Choose a room',
      supplier: 'Supplier',
      range: 'Range',
      rangePlaceholder: 'Choose a range',
      cancel: 'Cancel',
      publish: 'Publish',
      requiredError: 'All fields are required, including at least one image.',
      missingProduct: 'Product not found.',
      loadError: 'Unable to load the product.',
      imageDeleteError: 'Unable to remove the image.',
      saveError: 'Unable to save the product.',
      serverErrorTitle: 'A problem occurred while loading this page',
      serverErrorMessage: 'A technical issue prevented this page from loading. Try reloading this page or opening another page.',
      retry: 'Try again',
    },
  },
};

export function normalizeSupplierLanguage(language) {
  return String(language || '').toLowerCase().startsWith('ang') || String(language || '').toLowerCase().startsWith('en')
    ? 'en'
    : 'fr';
}

export function getSupplierLanguage(adminData) {
  return normalizeSupplierLanguage(adminData?.supplierSettings?.settings?.language);
}

export function getSupplierTranslations(adminDataOrLanguage) {
  const language = typeof adminDataOrLanguage === 'string'
    ? normalizeSupplierLanguage(adminDataOrLanguage)
    : getSupplierLanguage(adminDataOrLanguage);

  return SUPPLIER_TRANSLATIONS[language] || SUPPLIER_TRANSLATIONS.fr;
}
